
service: opensopt-api
app: sls-app
org: matheusdaluzcosta

provider:
  name: aws
  runtime: python2.7

functions:
  get:
    handler: handler.get_autoscale_groups_openspot
  enable:
     handler: handler.enable_openspot_in_autoscale